### ISSUE TITLE
Crashes when flicking through timetables provided on install

### ISSUE THREAD

**Issue by The-Dum-Gamer** [EratoNysiad/ScheduledDispatchScheduler#1]
Error

drawGraph.lua:18: 'for' limit must be a number

Traceback

drawGraph.lua:18: in function 'drawGraph'
main.lua:239: in function 'draw'
[C]: in function 'xpcall'

**Comment by EratoNysiad** [comment]
Fixed: Number of Timetables ever being a non-integer value
